### PR TITLE
Fix file load order

### LINKED ISSUE #8: Order of files loaded
Hi!

I noticed while working on #7 that the order in which files are loaded is undefined. I think it would be good if users can rely on a particular order, especially with #7 but maybe even without it. It seems like this might be intended from the code as well, since the list of "basenames" is reversed so that `default` comes first.

 I tried a bit but didn't see immediately what would be the cleanest way to fix this. Right now a dictionary of `filename: contents` is passed from `SafariExtensionHandler.swift`to `script.js`. My thought was to replace this with an array of `(filename, contents)` tuples, but you can't pass a tuple array to JavaScript I think.

I've enjoyed using the app and looking at the code, thank you.

### PR DESCRIPTION
**Pull request by ernstwi**
Fixes #8

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Super neat work!

File: Source/Extension/script.js [hunk 1]
```diff
@@ -10,10 +10,11 @@ safari.self.addEventListener("message", ({name, message}) => {
 const messageHandlers = {
   onload: message => {
     Object.entries(message).forEach(([fileType, files]) => {
-      Object.entries(files).forEach(([fileName, content]) => {
+      for (let f of files) {
+        let fileName = f[0]; content  = f[1]
         console.log(`Injecting ${fileName}`)
         fileTypeHandlers[fileType](content)
-      })
+      }
```
[the remark this answers is not in the document]
Comment (ernstwi) [reply Source/Extension/script.js]: Thanks, this is much better!

**Comment by ernstwi** [comment]
The tuple array would have been nice but didn't work unfortunately, it gave an error message about the passed data not conforming to `NSSecureCoding`.

(Not sure by the way if you prefer to add a commit here for the proposed change or do an --amend, I went with --amend.)

File: Source/Extension/SafariExtensionHandler.swift [hunk 2]
```diff
@@ -19,12 +17,12 @@ class SafariExtensionHandler: SFSafariExtensionHandler {
 
             let basenames = fileBasenames(forHost: host)
 
-            let keysWithValues = Config.FileType.allCases.map { fileType -> (Type, [Name: Content]) in
-                let files: [Name: Content]
+            let keysWithValues = Config.FileType.allCases.map { fileType -> (Type, [[String]]) in
+                let files: [[String]]
```
Comment (fphilipe) [inline Source/Extension/SafariExtensionHandler.swift]: I have to say that the code lost quite a bit of self-documentation.

What do you think of the following?

Keep the type aliases and use `[(Name, Content)]` instead of `[Name: Content]`. Then, only when passing the data to JS we transform the values:

```swift
page.dispatchMessageToScript(
    withName: "onload",
    userInfo: data.mapValues { $0.map(convertTupleToArray) }
)
```

```swift
func convertTupleToArray<T>(_ tuple: (T, T)) -> [T] {
    let (a, b) = tuple
    return [a, b]
}
```

Comment (ernstwi) [reply Source/Extension/SafariExtensionHandler.swift]: For sure, I see your point. It's a trade-off, I did consider this but decided on the more economic but less readable solution of using arrays all the way through. I'll leave the decision to you of course, but I would personally leave it as is I think.

You should feel free to make these edits, I left the PR open to edits so you can commit directly to my fork here if that's convenient.

**Comment by fphilipe** [comment]
@ernstwi, thanks for your contribution!

FYI, I've adjusted the implementation and introduced a `File` struct (in case you're curious) 😊

**Comment by gingerbeardman** [comment]
Thanks to both for this

**Comment by sn0wyfall** [comment]
@ernstwi  For someone who isn't as technically inclined, is there any documentation on how the the styles are loaded? I'm trying to style `localhost:8888` with multiple styles. I added one style which is called `localhost.css` and it works fine (of course I can't add the colon to the filename). I'm wondering how I would load a second style after this one. 

Worst case scenario I could possibly merge the two styles, and I'm assuming the style I want loaded last I'd put at the bottom?

**Comment by ernstwi** [comment]
The loading is as described in the app:

Screenshot 2020-06-27 at 11 36 31

In other words the domain name is split into parts on `.` and the more specific file name (more matching parts) is loaded later.

`localhos.css` would not match your URL. What you want is to load multiple stylesheets for one URL? The natural way to do this would be to use the same stylesheet. The CSS is loaded top to bottom, so lower rules have precedence, yup.

In normal circumstances you could use [`@import`](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) to split the CSS across multiple files, but I'm pretty sure this is not supported in PageExtender.

**Comment by sn0wyfall** [comment]
@ernstwi Awesome! I'll try that then. Thank you very much for the info
